### ISSUE TITLE
IDEA

### ISSUE THREAD

**Issue by lambdafu** [hannob/pgpbugs#7]
This is the paper that broke IDEA: https://link.springer.com/article/10.1007/s00145-013-9162-9

**Comment by hannob** [comment]
I'm not sure this fits. From what I understand and according to wikipedia [1] IDEA is still not really "broken" and these are theoretical attacks. I think if we add all theoretical results against any cipher supported by pgp that would clutter the list quite a bit.

Also I believe IDEA fell out of fashion in PGP not due to security issues, but due to patents.

Reopen if you disagree.

[1] https://en.wikipedia.org/wiki/International_Data_Encryption_Algorithm#Security
